export default [
  {
    id: 11,
    thumbnail: "me.webp",
    acccountLogo: "lekan.jpg",
    title: " COVID-19 is not over yet",
    accountName: "Olalekan Emmanuel",
    duration: "1:54",
    views: "15k views",
    verified: false,
    postedAt: "1 year ago",
  },

  {
    id: 1,
    thumbnail: "modric.webp",
    acccountLogo: "modric-logo.jpg",
    title: "The 10 of the 10: Luka modric",
    accountName: "Laliga Santander",
    duration: "5:41",
    views: "65k views",
    verified: true,
    postedAt: "11 days ago",
  },

  {
    id: 2,
    thumbnail: "lively.webp",
    acccountLogo: "lively-logo.jpg",
    title: "MR FESTUS THE BEST DRESSER !!! |MC LIVELY",
    accountName: "MC LIVELY",
    duration: "2:59",
    views: "11k views",
    verified: false,
    postedAt: "12 hours ago",
  },

  {
    id: 3,
    thumbnail: "ling.webp",
    acccountLogo: "ling-logo.jpg",
    title: "Do you brush your teeth before or after breakfast?!",
    accountName: "Ling and Lamb",
    duration: "12:03",
    views: "100k views",
    verified: false,
    postedAt: "7 days ago",
  },

  {
    id: 4,
    thumbnail: "woli.webp",
    acccountLogo: "woli-logo.jpg",
    title: "Neighbour's Hood | Episode 14",
    accountName: "AyoAjewole Woliagba YPM",
    duration: "17:05",
    views: "3.2k views",
    verified: true,
    postedAt: "4 hours ago",
  },

  {
    id: 5,
    thumbnail: "scrimba.webp",
    acccountLogo: "coding-logo.jpg",
    title: "Css cursor with HTML, CSS || Complete code",
    accountName: "codedesigner",
    duration: "5:05",
    views: "981 views",
    verified: false,
    postedAt: "5 days ago",
  },

  {
    id: 6,
    thumbnail: "fpl.webp",
    acccountLogo: "fpl-logo.jpg",
    title:
      "FPL TEAM SELECTION GAMEWEEK 2 | FANTASY PREMIER LEAGUE 2022/23 TIPS",
    accountName: "Let's Talk FPL",
    duration: "18:35",
    views: "200k views",
    verified: false,
    postedAt: "3 days ago",
  },

  {
    id: 7,
    thumbnail: "vini.webp",
    acccountLogo: "vini-logo.jpg",
    title: "TOP 50 Incredible Goals of The Season 20222",
    accountName: "SEN31 Extra",
    duration: "10:04",
    views: "768k views",
    verified: true,
    postedAt: "2 months ago",
  },

  {
    id: 8,
    thumbnail: "kova.webp",
    acccountLogo: "kova-logo.jpg",
    title:
      "Frenkie De Jong & Mateo Kovacic - A Masterclass in Beating The Press ",
    accountName: "Nino12x",
    duration: "10:08",
    views: "102k views",
    verified: false,
    postedAt: "1 day ago",
  },

  {
    id: 9,
    thumbnail: "cat.webp",
    acccountLogo: "cat-logo.jpg",
    title: "cat valentine being cat valentine for 1 minute",
    accountName: "love luna",
    duration: "1:25",
    views: "45k views",
    verified: false,
    postedAt: "3 weeks ago",
  },

  {
    id: 10,
    thumbnail: "remote.webp",
    acccountLogo: "woli-logo.jpg",
    title: "PASTOR REMOTE IN CHURCH AGAIN",
    accountName: "AyoAjewole Woliagba YPM",
    duration: "42:37",
    views: "407k views",
    verified: true,
    postedAt: "11 days ago",
  },
];